# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/pipeline-library

variables:
# PROJECT VARIABLES #
# projectName:
# appName: 
  projectName: Microservices
  appName: hellomicroservice
  buildTool: maven

stages:
- template: CD/CD-Pipeline-Template.yml@templates
  parameters:
    projectName: ${{ variables.projectName }}
    appName: ${{ variables.appName }}