apiVersion: v1
kind: Service
metadata:
    name: hellomicroservice-service
    namespace: microservices-dev
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: hellomicroservice-app